name: ihun_shop
description: A stylish mobile app built for selling trendy shoes. Seamlessly integrated with a custom backend API

version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_vector_icons: ^2.0.0
  google_fonts: ^5.1.0
  flutter_staggered_grid_view: ^0.4.0
  cached_network_image: ^3.2.3
  flutter_rating_bar: ^4.0.1
  flutter_slidable: ^3.0.0
  flutter_screenutil: ^5.8.4
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  provider: ^6.0.5
  
  dots_indicator: ^3.0.0
  carousel_slider: ^4.2.1
  dio: ^5.3.0
  shared_preferences: ^2.2.0
  fluttertoast: ^8.2.2
  http: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  mockito: ^5.4.2
  build_runner: ^2.4.6

flutter:

  uses-material-design: true


  assets:
    - assets/images/


 